DEBUG = true

task = "anomaly_detection" # options: forecasting, anomaly_detection, imputation, classification
model = "timellm"    # options: timellm, dlinear

history_len = 96
pred_len = 96


[data]
dataset = "ECG"
mode = "univariate"
cols = "all"
normalize = false
step = 48


[training]
epochs = 1
batch_size = 16
optimizer = "adam"
learning_rate = 0.0001
dropout = 0.1

loss = "mse"


[models.timellm]
d_model = 16
n_heads = 8
d_ff = 32
num_tokens = 1000

[models.timellm.patching]
patch_len = 16
stride = 8

[models.timellm.llm]
enabled = false
llm = "state-spaces/mamba-1.4b-hf"
load_in_4bit = false
llm_layers = 4


[models.dlinear]
moving_avg = 25
individual = false


[setup]
seed = 0
device = "cuda:0"
num_workers = 8
