DEBUG = true

task = "forecasting" # options: forecasting, anomaly_detection, imputation, classification
model = "timellm"    # options: timellm, gpt4ts, dlinear

history_len = 96
pred_len = 48


[data]
dataset = "ECG"
mode = "multivariate"
cols = "all"
normalize = true
step = 24


[training]
epochs = 1
batch_size = 16
optimizer = "ranger"
learning_rate = 0.001
dropout = 0.1
loss = "mse"

eval_metric = "mse"
eval_metric_direction = "min"


[tasks.segmentation]
mode = "boundary-prediction"
# mode = "steps-to-boundary"
distance_thresh = 300


[models.timellm]
d_model = 16
n_heads = 8
d_ff = 32
num_tokens = 1000
covariate_mode = "add"    # options: univariate, concat, add, interleave, independent

[models.timellm.patching]
patch_len = 16
stride = 8

[models.timellm.llm]
enabled = false
llm = "state-spaces/mamba-1.4b-hf"
load_in_4bit = false
llm_layers = 2


[models.gpt4ts]
d_ff = 768
d_model = 768
gpt_layers = 6
train_mlp = false

[models.gpt4ts.patching]
patch_len = 1
stride = 1


[models.dlinear]
moving_avg = 25
individual = false


[setup]
seed = 0
device = "auto"
dtype = "bf16"
num_workers = 0
logger = "tensorboard"
