DEBUG = false

task = "anomaly_detection"
model = "medtsllm"

history_len = 128
pred_len = 128


[data]
dataset = "ECG"
mode = "multivariate"
cols = "all"
normalize = true
step = 128


[training]
epochs = 10
batch_size = 16
optimizer = "adam"
learning_rate = 1e-4
dropout = 0.1
loss = "mse"

eval_metric = "recon_mse"
eval_metric_direction = "min"


[datasets.ECG]
version = "v2"


[tasks.anomaly_detection]
threshold = "auto"
score_metric = "mse"
normalize_by_feature = true
normalize_moving_window = 0


[models.timellm]
d_model = 32
d_ff = 64
n_heads = 8
num_tokens = 1024
covariate_mode = "concat"
embedding_downsample_mode = "linear"

[models.timellm.patching]
patch_len = 16
stride = 8

[models.timellm.prompting]
dataset = true
clip = false
task = true
input_stats = false
examples = false
input_stats_dim = "all"
input_stats_select = "all"
example_pool = 1024

[models.timellm.llm]
enabled = true
llm = "meta-llama/Llama-2-7b-hf"
load_in_4bit = false
load_in_8bit = false
llm_layers = -1


[setup]
seed = 0
device = "auto"
dtype = "mixed"
num_workers = "auto"
logger = "wandb"
