DEBUG = false

task = "segmentation"
model = "medtsllm"

history_len = 256
pred_len = 256


[data]
dataset = "ECG"
mode = "multivariate"
cols = "all"
normalize = true
step = 256


[training]
epochs = 10
batch_size = 16
optimizer = "adam"
learning_rate = 1e-4
dropout = 0.1
loss = "bce"

eval_metric = "segment_miou"
eval_metric_direction = "max"


[datasets.ECG]
version = "v2"


[tasks.segmentation]
mode = "boundary-prediction"
distance_thresh = "auto"


[models.timellm]
d_model = 32
d_ff = 64
n_heads = 8
num_tokens = 1024
covariate_mode = "concat"
embedding_downsample_mode = "linear"

[models.timellm.patching]
patch_len = 16
stride = 8

[models.timellm.prompting]
dataset = true
clip = true
task = true
input_stats = false
examples = false
input_stats_dim = "all"
input_stats_select = "all"
example_pool = 0

[models.timellm.llm]
enabled = true
llm = "meta-llama/Llama-2-7b-hf"
load_in_4bit = false
load_in_8bit = false
llm_layers = -1


[setup]
seed = 0
device = "auto"
dtype = "mixed"
num_workers = "auto"
logger = "wandb"
